/lib/@DEBTRIPLE@/libhistory.so.8
/lib/@DEBTRIPLE@/libhistory.so.8.usr-is-merged
libreadline8t64
/lib/@DEBTRIPLE@/libreadline.so.8
/lib/@DEBTRIPLE@/libreadline.so.8.usr-is-merged
libreadline8t64
/lib64
/.lib64.usr-is-merged
base-files
/lib/@DEBTRIPLE@/libhistory.so.8.2
/lib/@DEBTRIPLE@/libhistory.so.8.2.usr-is-merged
libreadline8t64
/libx32
/.libx32.usr-is-merged
base-files
/lib/ld-linux-@ARCH@.so.1
/lib/ld-linux-@ARCH@.so.1.usr-is-merged
libc6
/lib32
/.lib32.usr-is-merged
base-files
/libo32
/.libo32.usr-is-merged
base-files
